// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApL_VqIdpvYVpmUsNtLIVD6rC_fNr5zFY',
    appId: '1:252600020571:web:7b49c6b7ea7941fdf6597e',
    messagingSenderId: '252600020571',
    projectId: 'ntr-study-hub-4df5f',
    authDomain: 'ntr-study-hub-4df5f.firebaseapp.com',
    storageBucket: 'ntr-study-hub-4df5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8HDwYf1ruGXeXhueN-sN5Wn3VhnfkuEM',
    appId: '1:252600020571:android:79fa1dc22fca3d8df6597e',
    messagingSenderId: '252600020571',
    projectId: 'ntr-study-hub-4df5f',
    storageBucket: 'ntr-study-hub-4df5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4g_FWriDWTQ5f7V3wL9Sm8LFTQqUQZ90',
    appId: '1:252600020571:ios:82064d93cadb3aaaf6597e',
    messagingSenderId: '252600020571',
    projectId: 'ntr-study-hub-4df5f',
    storageBucket: 'ntr-study-hub-4df5f.firebasestorage.app',
    iosBundleId: 'com.example.ntrAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4g_FWriDWTQ5f7V3wL9Sm8LFTQqUQZ90',
    appId: '1:252600020571:ios:82064d93cadb3aaaf6597e',
    messagingSenderId: '252600020571',
    projectId: 'ntr-study-hub-4df5f',
    storageBucket: 'ntr-study-hub-4df5f.firebasestorage.app',
    iosBundleId: 'com.example.ntrAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApL_VqIdpvYVpmUsNtLIVD6rC_fNr5zFY',
    appId: '1:252600020571:web:01e79c6151cb7b11f6597e',
    messagingSenderId: '252600020571',
    projectId: 'ntr-study-hub-4df5f',
    authDomain: 'ntr-study-hub-4df5f.firebaseapp.com',
    storageBucket: 'ntr-study-hub-4df5f.firebasestorage.app',
  );
}
